/**
 * Composable for bonus-related data and constants
 * Data based on the legacy builder system
 */

export type BonusType = 'civ' | 'uu' | 'castle' | 'imp' | 'team'

export interface BonusCard {
  id: number
  name: string
  description: string
  rarity: number
  edition: number
  imageVersion: number
}

export const rarityNames = ['Ordinary', 'Distinguished', 'Superior', 'Epic', 'Legendary'] as const
export const rarityCssClasses = ['common', 'uncommon', 'rare', 'epic', 'legendary'] as const

export const editionNames = ['Base Edition', 'First Edition'] as const

// Number of cards per bonus type
export const numCards = {
  civ: 363,
  uu: 88,
  castle: 60,
  imp: 59,
  team: 80
}

/**
 * Map round type index to bonus type
 * @param roundType - The draft round type (0-4)
 * @returns The corresponding BonusType
 */
export function roundTypeToBonusType(roundType: number): BonusType {
  const types: BonusType[] = ['civ', 'uu', 'castle', 'imp', 'team']
  return types[roundType] || 'civ'
}

// Maximum selections per bonus type
// maxUniqueSelections: how many different bonuses can be selected
// maxTotalSelections: total count including multipliers (null = no limit on total)
export const maxSelections = {
  civ: { maxUniqueSelections: 6, maxTotalSelections: 1530 }, // 6 unique * 255 max multiplier each
  uu: { maxUniqueSelections: 1, maxTotalSelections: 1 },
  castle: { maxUniqueSelections: 1, maxTotalSelections: 255 },
  imp: { maxUniqueSelections: 1, maxTotalSelections: 255 },
  team: { maxUniqueSelections: 1, maxTotalSelections: 255 }
}

// Image prefix for each bonus type
export const imagePrefix: Record<BonusType, string> = {
  civ: 'bonus',
  uu: 'uu',
  castle: 'castle',
  imp: 'imp',
  team: 'team'
}

/**
 * Get the base URL for assets (handles static assets from /public)
 * @returns The base URL prefix for image assets
 */
function getAssetBaseUrl(): string {
  // Static assets (images, etc.) are served from the main /public folder
  // at the root path, not from Nuxt's /v2 path
  return ''
}

/**
 * Get the image URL for a bonus card
 * @param type - The type of bonus (civ, team, etc.)
 * @param id - The card ID
 * @param version - Image version number for cache busting (from card metadata, defaults to 0)
 * @returns The URL path to the card image
 */
export function getBonusImageUrl(type: BonusType, id: number, version: number = 0): string {
  const prefix = imagePrefix[type]
  const baseUrl = getAssetBaseUrl()
  return `${baseUrl}/img/compressedcards/${prefix}_${id}_v${version}.jpg`
}

/**
 * Get the frame image URL for a rarity
 */
export function getFrameUrl(rarity: number): string {
  const baseUrl = getAssetBaseUrl()
  return `${baseUrl}/img/frames/frame_${rarityCssClasses[rarity]}.png`
}

/**
 * Get the edition badge image URL
 */
export function getEditionUrl(edition: number): string {
  const editionIndex = edition <= 0 ? 0 : edition
  const baseUrl = getAssetBaseUrl()
  return `${baseUrl}/img/editions/edition_${editionIndex}.png`
}

// Civilization Bonuses, Unique Units, Castle Techs, Imperial Techs, Team Bonuses
// Card text, card rarity, card edition (negative => which vanilla civ), image versioning (for caching)
const cardDescriptions: [string, number, number, number][][] = [
  // Civ Bonuses (index 0)
  [
    ["Town Centers cost -50% wood starting in the Castle Age", 1, -1, 0],
    ["Foot archers (except skirmishers) +1 range in Castle and Imperial Age (+2 total)", 3, -1, 0],
    ["Shepherds work 25% faster", 1, -1, 0],
    ["Castles cost -15% in Castle, -25% in Imperial Age", 2, -2, 0],
    ["Mounted units +20% hit points starting in Feudal Age", 3, -2, 0],
    ["Foragers work 10% faster", 1, -2, 0],
    ["Loom can be researched instantly", 0, -3, 0],
    ["Villagers +5 attack vs. wild boar; hunters carry +15 meat; hunt contains +20% meat", 1, -3, 0],
    ["+10 population in Imperial Age", 0, -3, 0],
    ["Infantry +1 attack vs. buildings per age (starting from Feudal Age)", 0, -3, 0],
    ["Infantry cost -15% in Dark, -20% in Feudal, -25% in Castle, -30% in Imperial Age", 4, -3, 0],
    ["Monks double healing range", 0, -4, 0],
    ["Towers garrison 2x units; Town Centers garrison +10", 0, -4, 0],
    ["Farms cost -40%", 2, -4, 0],
    ["Barracks and Stable units +1 armor in Castle and Imperial Age (+2 total)", 1, -4, 0],
    ["Economic drop-off buildings cost -50%", 1, -5, 0],
    ["Fishing Ships 2x hit points; +2P armor; work rate +5% Dark, +10% Feudal, +15% Castle, +20% Imperial Age", 2, -5, 0],
    ["Infantry attack 33% faster starting in Feudal Age", 1, -5, 0],
    ["Start with +3 villagers, -50 wood, -200 food; Town Centers support 15 population and +7 LOS", 2, -6, 0],
    ["Demolition ships +50% hit points", 0, 1, 0],
    ["Technologies cost -5% Feudal, -10% Castle, -15% Imperial Age", 2, -6, 0],
    ["Buildings +10% HP Dark, +20% Feudal, +30% Castle, +40% Imperial Age", 1, -7, 0],
    ["Fire ships attack 25% faster", 0, -7, 0],
    ["Camel Riders, Skirmishers, Pikemen, Halberdiers cost -25%", 2, -7, 0],
    ["Start with +50 wood, food", 0, -8, 0],
    ["Town Center, Dock 2x hit points", 0, -8, 0],
    ["Town Center, Dock work rate +5% Dark, +10% Feudal, +15% Castle, +20% Imperial Age", 2, -8, 0],
    ["Market costs -100 wood; market trade cost only 5%", 1, -9, 0],
    ["Transport Ships 2x hit points, +20 carry capacity", 0, -9, 0],
    ["Galleys attack 25% faster", 1, -9, 0],
    ["Camel units +25% hit points", 2, -9, 0],
    ["Gunpowder units +25% hit points", 2, -10, 0],
    ["Gold miners work 20% faster", 1, -10, 0],
    ["Scout Cavalry, Light Cavalry, Hussar +1 pierce armor", 1, -10, 0],
    ["Warships cost -15% Feudal Age, -15% Castle Age, -20% Imperial Age", 2, -11, 0],
    ["Infantry +20% hit points starting in Feudal Age", 1, -11, 0],
    ["Cavalry archers fire 25% faster", 2, -12, 0],
    ["Hunters work 40% faster", 3, -12, 0],
    ["Light Cavalry, Hussars, Steppe Lancers +20/30% hit points in Castle/Imperial Age", 1, -12, 0],
    ["Infantry moves +5/10/15/20% faster in Dark/Feudal/Castle/Imperial Age", 1, -13, 0],
    ["Lumberjacks work 15% faster", 2, -13, 0],
    ["Siege units fire 25% faster", 2, -13, 0],
    ["Can steal sheep, and sheep within one unit's LoS cannot be stolen", 0, -13, 0],
    ["Missionaries can be trained in monasteries", 1, -14, 0],
    ["Start with +50 gold", 0, -15, 0],
    ["+5 Monk hit points for each Monastery technology", 3, -15, 0],
    ["Start with +1 villager, but -50 food", 1, -16, 0],
    ["Cavalry Archers cost -10% Castle, -20% Imperial Age", 2, -17, 0],
    ["Ranged Soldiers, Infantry, and Warships cost -50% wood", 2, -18, 0],
    ["Archer armor upgrades free", 1, -18, 0],
    ["Can train Turtle Ships in docks", 0, -18, 0],
    ["Can recruit Longboats from docks", 2, -11, 0],
    ["Gunpowder units cost -20%", 2, -19, 0],
    ["Can upgrade Heavy Camel Riders to Imperial Camel Riders", 2, -20, 0],
    ["Fishermen work 10% faster", 0, 1, 0],
    ["Stable units +1P armor in Castle and Imperial Age (+2 total)", 2, 1, 0],
    ["Villagers cost -8% Dark, -13% Feudal, -18% Castle, -23% Imperial Age", 2, -20, 0],
    ["Military units cost -10, 15, 20, 25% food in Dark, Feudal, Castle, Imperial", 4, -21, 0],
    ["Buildings cost -15% stone", 1, -21, 0],
    ["Houses support 10 population", 0, -21, 0],
    ["Villagers affected by Blacksmith upgrades starting in the Castle Age", 0, -21, 0],
    ["Can recruit slingers from Archery Ranges", 1, -21, 0],
    ["Villagers kill wolves with 1 strike", 0, -22, 0],
    ["Scout Cavalry, Light Cavalry, Hussar cost -15%", 1, -22, 0],
    ["Siege Workshop units 15% cheaper", 1, -23, 0],
    ["All units cost -20% gold", 4, -24, 0],
    ["Foragers generate a trickle of wood (33%)", 1, -24, 0],
    ["Ships +10% HP", 1, -24, 0],
    ["Can build Feitoria in Imperial Age", 3, -24, 0],
    ["Can build Caravels in docks", 1, -24, 0],
    ["Foot archers fire 18% faster", 2, -25, 0],
    ["Receive +100 gold, +100 food when advancing to the next age", 2, -25, 0],
    ["Pikeman upgrade free", 0, -25, 0],
    ["Buildings cost -15% wood", 1, -26, 0],
    ["Barracks units +1 pierce armor per age (starting from Feudal Age)", 2, -26, 0],
    ["Villagers drop off 10% more gold", 1, -26, 0],
    ["Villagers move 5% faster in Dark Age, 10% faster in Feudal Age", 1, -27, 0],
    ["Ships move 10% faster", 0, -27, 0],
    ["Stable units cost -15% in Castle, -20% in Imperial Age", 3, -27, 0],
    ["Melee elephant units move 10% faster", 1, -28, 0],
    ["Villagers can garrison in Houses", 0, -28, 0],
    ["No buildings required to advance to the next age or to unlock other buildings", 2, -28, 0],
    ["Advance to the next age 66% faster", 3, -29, 0],
    ["Elephant units cost -25% Castle, -35% in Imperial Age", 4, -29, 0],
    ["Fish Traps cost -33% and provide +200% food", 0, -29, 0],
    ["Foot Archers and Condottieri +1 melee/+1 pierce armor", 1, -19, 0],
    ["Lumber Camp upgrades free", 2, -30, 0],
    ["Infantry +1 attack per age (starting in the Feudal Age)", 1, -30, 0],
    ["Monastery technologies cost -50%", 1, -30, 0],
    ["Enemy positions are revealed at the start of the game", 0, -31, 0],
    ["Archery Range units and Fire Lancers +20% HP", 2, -31, 0],
    ["Militia-line upgrades free", 3, -32, 0],
    ["Town Centers cost -50% stone starting in the Castle Age", 0, -32, 0],
    ["Can build Krepost", 2, -32, 0],
    ["Livestock animals last +50% longer", 0, -33, 0],
    ["Units deal +25% damage when fighting from higher elevation", 0, -33, 0],
    ["Thumb Ring, Parthian Tactics free", 1, -33, 0],
    ["Mounted units 5% faster each age (starting in Feudal Age)", 2, -34, 0],
    ["Additional Town Center can be built in the Feudal Age", 1, -34, 0],
    ["Siege Workshop and Battering Ram available in the Feudal Age; Capped Ram upgrade available in Castle Age", 1, -34, 0],
    ["Receive +100 food per Town Center", 1, -35, 0],
    ["Spearmen and Skirmishers move 10% faster", 1, -35, 0],
    ["Each garrisoned relic gives +1 attack to Knights and Unique Unit (maximum +4)", 2, -35, 0],
    ["Cavalier upgrade available in Castle Age", 2, -36, 0],
    ["Gunpowder units +25% attack", 2, -36, 0],
    ["Economic upgrades cost -33% food and available one age earlier", 2, -36, 0],
    ["Fortifications built 50%, Town Centers built 100% faster", 1, -37, 0],
    ["Soldiers receive 33% less bonus damage", 4, -37, 0],
    ["Farm upgrades provide +125% additional food", 0, -37, 0],
    ["Can build Donjon", 2, -37, 0],
    ["Farm upgrades free (require Mill)", 1, -2, 0],
    ["Forging, Iron Casting, Blast Furnace free", 1, -22, 0],
    ["Arson and Gambesons free", 1, -23, 0],
    ["Town Watch, Town Patrol free", 0, -7, 0],
    ["Murder Holes, Herbal Medicine free", 0, -4, 0],
    ["Chemistry free", 2, -10, 0],
    ["Light Cavalry and Hussar upgrades free", 1, -10, 0],
    ["Wheelbarrow, Hand Cart free", 3, -11, 0],
    ["Tower upgrades free (Bombard Tower requires Chemistry)", 2, -18, 0],
    ["Conscription free", 0, -31, 0],
    ["Farmers work 15% faster", 2, -23, 0],
    ["Advancing to the next age costs -15%", 1, -19, 0],
    ["Fishing Ships cost -15%", 1, -19, 0],
    ["Dock and University technologies cost -33%", 0, -19, 0],
    ["Advancing to Imperial Age costs -33%", 0, -7, 0],
    ["Blacksmith upgrades don't cost gold", 1, -14, 0],
    ["Gunpowder units fire 18% faster", 1, -14, 0],
    ["Builders work 30% faster", 1, -14, 0],
    ["Military units train +15% faster", 1, -15, 0],
    ["Villagers carry +3", 1, -15, 0],
    ["Trebuchet units fire more accurately at units and small targets", 0, -17, 0],
    ["Do not need houses, -100 wood", 1, -17, 0],
    ["Resources last 15% longer", 1, -16, 0],
    ["Foot archers and skirmishers cost -10% Feudal, -20% Castle, -30% Imperial Age", 3, -16, 0],
    ["Lumberjacks generate food in addition to wood", 2, -49, 0],
    ["Stone miners work 20% faster", 1, -18, 0],
    ["Economic upgrades cost no wood and research +100% faster", 0, -31, 0],
    ["Blacksmith and Siege Workshop technologies cost -50% food", 1, -32, 0],
    ["Stable technologies cost -50%", 1, -36, 0],
    ["New Town Centers spawn 2 sheep starting in the Castle Age", 0, -33, 0],
    ["Wonders don't cost wood and provide +50 to population limit (max 1)", 2, 1, 0],
    ["Villagers +3 HP per economic tech researched", 1, 1, 0],
    ["Villagers regenerate 10 HP/min in Feudal, 15 in Castle, 20 in Imperial Age", 1, -38, 0],
    ["Military buildings built 100% faster", 0, 1, 0],
    ["Resource drop-off buildings provide +5 population space", 0, 1, 0],
    ["Ballistics researched instantly and costs no wood", 1, 1, 0],
    ["Archer-line upgrades free", 2, 1, 0],
    ["Skirmisher-line upgrades free", 1, 1, 0],
    ["Camel-line upgrades free", 2, 1, 0],
    ["Infantry Armor upgrades free", 1, -29, 0],
    ["Cavalry Armor upgrades free", 3, 1, 0],
    ["Fletching, Bodkin Arrow, Bracer free", 4, 1, 0],
    ["Redemption free", 2, 1, 0],
    ["Squires free", 0, 1, 0],
    ["Eagle-line upgrades free", 3, 1, 0],
    ["Battle Elephant upgrades free", 3, 1, 0],
    ["Sanctity, Fervor free", 2, 1, 0],
    ["Atonement, Illumination free", 1, 1, 0],
    ["Theocracy, Block Printing free", 2, 1, 0],
    ["Hoardings, Fortified Wall free", 0, 1, 0],
    ["Masonry, Architecture free", 0, 1, 0],
    ["Mining Camp technologies free", 2, -39, 0],
    ["Sappers, Treadmill Crane free", 0, 1, 0],
    ["Galleon free", 1, 1, 0],
    ["Careening, Dry Dock free", 0, 1, 0],
    ["Fast Fire Ship free", 1, 1, 0],
    ["Heavy Demolition Ship free", 1, 1, 0],
    ["Gillnets free", 1, 1, 0],
    ["War Galley free", 1, 1, 0],
    ["Heavy Cavalry Archer free", 2, 1, 0],
    ["Ram-line upgrades free", 3, 1, 0],
    ["Trade units 20% faster", 2, 1, 0],
    ["Squires affects foot archers and skirmishers", 1, 1, 0],
    ["Shock Infantry +5% speed per age (starting in Feudal Age)", 2, 1, 0],
    ["Start with +150 wood", 1, 1, 0],
    ["Start with +100 stone", 1, -37, 0],
    ["Start with +50 wood, +50 stone", 0, 1, 0],
    ["Start with +70 food, +30 gold", 1, 1, 0],
    ["Monk units train 66% faster", 1, 1, 0],
    ["Trebuchet units train 50% faster", 0, 1, 0],
    ["Cavalry Archers train 33% faster", 0, 1, 0],
    ["Land explosive units train 200% faster", 0, 1, 0],
    ["Land explosive units +8 pierce armor", 0, 1, 0],
    ["Bloodlines free in Castle Age", 0, 1, 0],
    ["Galleys +1 range", 1, 1, 0],
    ["Receive +100 wood, +100 stone when advancing to the next age", 2, 1, 0],
    ["Receive +400 food upon advancing to Castle Age", 2, 1, 0],
    ["Receive +350 stone upon advancing to Castle Age", 2, 1, 0],
    ["Receive +250 wood upon reaching Feudal Age", 2, 1, 0],
    ["Receive +500 gold upon reaching Imperial Age", 2, 1, 0],
    ["+100 HP and pierce armor for monks with relics", 0, 1, 0],
    ["Land explosive units 2x HP", 0, 1, 0],
    ["Town Centers spawn 2 villagers when the next Age is reached", 3, -41, 0],
    ["Can recruit Warrior Priests", 1, -44, 0],
    ["Castles and Kreposts +2000 HP", 1, 1, 0],
    ["Blacksmith upgrades are free an age after they become available", 1, 1, 0],
    ["Barracks cost -75 wood", 1, 1, 0],
    ["Stables cost -75 wood", 1, -34, 0],
    ["Archery Ranges cost -75 wood", 1, -34, 0],
    ["Monasteries cost -100 wood", 1, 1, 0],
    ["Siege Workshops cost -100 wood", 1, 1, 0],
    ["Military Buildings cost -50 wood", 1, 1, 0],
    ["Blacksmiths and Universities cost -100 wood", 0, -39, 0],
    ["Infantry +1 attack vs. villagers per age (starting in Dark Age)", 0, 1, 0],
    ["Fishermen and Fishing Ships carry +15", 1, -40, 0],
    ["Galleys +1 attack", 1, 1, 0],
    ["Steppe Lancers +10 attack vs. villagers", 2, 1, 0],
    ["Steppe Lancers attack 33% faster", 1, 1, 0],
    ["Elephant units attack 25% faster", 1, 1, 0],
    ["Stone Walls available in Dark Age", 0, 1, 0],
    ["Receive +50 food, +50 wood, +50 stone, +50 gold when advancing to the next age", 2, 1, 0],
    ["Villagers return 25 food on death", 0, 1, 0],
    ["Camel units attack 20% faster", 1, -20, 0],
    ["Mangonels can cut trees", 1, 1, 0],
    ["Can train a free Siege Tower in Feudal Age; Siege Towers cost -50%", 2, 1, 0],
    ["Rams, Siege Towers x2 garrison space", 2, 1, 0],
    ["Towers support 15 population", 0, 1, 0],
    ["Gunpowder units move 20% faster", 2, 1, 0],
    ["Completed castles provide 400 gold as long as they stay standing", 1, 1, 0],
    ["Monk units move 20% faster", 2, -23, 0],
    ["Melee Cavalry gain +2 bonus damage vs Skirmishers", 0, 1, 0],
    ["Spearman- and Militia-line upgrades (except Man-at-Arms) available one age earlier", 1, -44, 0],
    ["Can buy cows in mills (10 gold)", 1, 1, 0],
    ["Start with an extra horse", 1, -17, 0],
    ["Siege Towers 2x HP", 1, 1, 0],
    ["Siege Towers train 100% faster", 0, 1, 0],
    ["Siege units cost -33% wood", 1, -40, 0],
    ["Cannon Galleons benefit from Ballistics (fire faster, more accurately)", 1, -14, 0],
    ["Warships +10 attack vs. villagers", 0, 1, 0],
    ["Rams generate stone by ramming", 3, 1, 0],
    ["Town Centers +50% work rate in Imperial Age", 2, 1, 0],
    ["Feudal Age costs -25%", 1, 1, 0],
    ["Spearmen and Skirmishers train 50% faster", 1, 1, 0],
    ["Spearmen +25% HP", 1, 1, 0],
    ["Market techs cost no gold", 0, 1, 0],
    ["Trees contain double the amount of wood", 1, 1, 0],
    ["Stone resources last 30% longer", 1, 1, 0],
    ["Gold resources last 30% longer", 1, 1, 0],
    ["Berries contain +35% more food", 1, 1, 0],
    ["Can upgrade Fortified Walls to City Walls in Imperial Age", 2, 1, 0],
    ["Fish contain +35% more food", 1, 1, 0],
    ["Units garrisoned in buildings heal 2x faster", 0, 1, 0],
    ["Repairers work 100% faster", 1, 1, 0],
    ["Skirmishers +1 attack vs. infantry", 0, 1, 0],
    ["Archery Range units +1 attack", 3, 1, 0],
    ["Archery range units +1 melee armor per age (starting in Feudal)", 2, 1, 0],
    ["Siege units +1 pierce armor in Castle and Imperial (+2 total)", 1, 1, 0],
    ["Parthian Tactics available in Castle Age", 1, 1, 0],
    ["Castle Age costs -25%", 1, 1, 0],
    ["Cavalry +1 attack", 1, 1, 0],
    ["Forging, Iron Casting, Blast Furnace add +1 damage vs. buildings", 1, 1, 0],
    ["All buildings +3 pierce armor", 0, 1, 0],
    ["Foot archers +5% speed per age (starting in Feudal)", 2, 1, 0],
    ["Foot archers and skirmishers +1 attack vs. villagers", 1, 1, 0],
    ["Gunpowder +10 attack vs. camels", 0, 1, 0],
    ["Shock Infantry +6 attack vs. stone defenses", 0, 1, 0],
    ["Scouts, Light Cavalry, Hussar +4 attack vs. stone defenses", 0, 1, 0],
    ["All villagers work 5% faster", 2, -43, 0],
    ["Villagers +1 carry capacity per Town Center technology researched", 1, 1, 0],
    ["Farms 10x HP", 0, 1, 0],
    ["Militia-line +2 attack vs. cavalry", 1, 1, 0],
    ["Steppe Lancer upgrades free", 1, 1, 0],
    ["Steppe Lancers +2 pierce armor", 1, 1, 0],
    ["Castles and Kreposts deal large damage against buildings", 2, 1, 0],
    ["All villagers work 10% faster in Imperial Age", 2, 1, 0],
    ["Outposts +5 garrison capacity", 0, 1, 0],
    ["Villagers +10 pierce armor while building or repairing", 0, 1, 0],
    ["Castles and Kreposts support 50 population", 0, 1, 0],
    ["Bombard towers deal extra damage to rams", 1, 1, 0],
    ["Towers deal extra damage to cavalry", 2, 1, 0],
    ["Can build Monastery in Feudal Age; Monks recruited in Feudal Age have longer conversions and cannot pickup relics", 1, 1, 0],
    ["Scorpions, Ballista Elephants, and War Wagons train 50% faster", 0, 1, 0],
    ["Town Centers fire 25% faster", 0, 1, 0],
    ["Trebuchet units cost -50% gold", 0, 1, 0],
    ["All explosive units 2x blast radius", 0, 1, 0],
    ["Gunpowder units +8 attack vs. buildings", 0, 1, 0],
    ["Shock Infantry +1 pierce armor", 0, 1, 0],
    ["Gunpowder units +1 attack per university technology researched (cumulative)", 3, 1, 0],
    ["Buildings +3% HP per university technology researched (cumulative)", 1, 1, 0],
    ["Each monastery technology researched brings a monk to your cause", 3, 1, 0],
    ["Folwark replaces Mill", 1, -38, 0],
    ["Stone Miners generate gold in addition to stone", 2, -38, 0],
    ["Winged Hussar replaces Hussar", 1, -38, 0],
    ["Chemistry and Hand Cannoneer available in Castle Age", 1, -39, 0],
    ["Spearmen deals +25% bonus damage", 1, -39, 0],
    ["Fervor and Sanctity affects villagers", 0, -39, 0],
    ["Can upgrade Bombard Cannons to Houfnice", 3, -39, 0],
    ["Can build Caravanseri in Imperial Age", 1, -20, 0],
    ["Gunpowder units +1/+1P armor", 1, -20, 0],
    ["Receive +200 wood when advancing to the next age", 2, -40, 0],
    ["Barracks technologies cost -50%", 1, -40, 0],
    ["Skirmishers and Elephant Archers attack 25% faster", 1, -40, 0],
    ["Elephant units receive 25% less bonus damage and are more resistant to conversion", 1, -41, 0],
    ["Ships regenerate 15 HP per minute", 0, -41, 0],
    ["Start with 2 Forage Bushes", 1, -42, 0],
    ["Can garrison Mills with livestock to produce food", 1, -42, 0],
    ["Mounted units deal +20% bonus damage Feudal, +30% Castle, +40% Imperial Age", 1, -42, 0],
    ["Can garrison Docks with Fishing Ships", 1, -42, 0],
    ["Can train Thirisadai in docks", 1, -40, 0],
    ["Can recruit Shrivamsha Riders", 2, -42, 0],
    ["Can recruit Camel Scouts in Feudal Age", 1, -42, 0],
    ["Gain 20 gold for each technology researched", 1, -14, 0],
    ["Galley-line and Dromons +1/+1 armor", 1, -43, 0],
    ["Battle elephants +1/+1P armor", 2, -30, 0],
    ["Monk units +3/+3P armor", 2, -41, 0],
    ["Infantry receives double effect from Blacksmith armor upgrades", 3, -43, 0],
    ["Scorpions cost -60% gold and benefit from Ballistics research", 2, -43, 0],
    ["Legionary replaces Two-Handed Swordsman / Champion", 0, -43, 0],
    ["Can upgrade Heavy Scorpions to Imperial Scorpions", 3, 1, 0],
    ["Can upgrade Elite Battle Elephants to Royal Battle Elephants", 4, 1, 0],
    ["Can upgrade Elite Steppe Lancers to Royal Lancers", 3, 1, 0],
    ["Cavalry Archers +2 attack vs. Ranged Soldiers (except skirmishers)", 1, -5, 0],
    ["Wood and mining upgrades are 40% more effective, economic drop-off buildings cost -25%", 4, -44, 0],
    ["First religious building receives a free relic", 1, -44, 0],
    ["Savar replaces Paladin", 2, -8, 0],
    ["Galley-line and Dromons fire an additional projectile", 1, -44, 0],
    ["Fortified church replaces monastery", 2, -44, 0],
    ["Mule Carts replace Lumber Camps and Mining Camps", 1, -44, 0],
    ["Start with a Mule Cart", 2, -45, 0],
    ["Religious buildings provide Villagers in an 8 tile radius with +10% work rate", 1, -45, 0],
    ["Units and buildings receive -15% damage when fighting from higher elevation", 1, -45, 0],
    ["Mounted units regenerate 2/8/14 HP per minute, in the Feudal, Castle, Imperial Age", 3, -45, 0],
    ["Flaming Camels available in Siege Workshops in Imperial Age", 0, -33, 0],
    ["All buildings refund +1 stone per tile of foundation", 3, 1, 0],
    ["Villagers work faster when nearby other villagers", 2, 1, 0],
    ["Husbandry affects attack speed", 1, 1, 0],
    ["Trade yields 10% stone in addition to gold", 1, 1, 0],
    ["Blacksmith upgrades affect bonus damage", 3, 1, 0],
    ["Cavalry archers can dodge one projectile", 1, 1, 0],
    ["Farmers don't require Mills/Town Centers to drop off food", 1, -28, 0],
    ["Farms are smaller", 1, 1, 0],
    ["Archery range techs cost -50%", 0, 1, 0],
    ["Knights available in Feudal Age with 30HP", 2, 1, 0],
    ["Siege Towers can fire arrows", 2, 1, 0],
    ["Fire Lancers and Fire Ships move +5/10% faster in Castle/Imperial Age", 1, -6, 0],
    ["Archery Unit technologies at the Archery Range and Blacksmith cost -25%", 0, -49, 0],
    ["Siege Weapons and Siege Warships move +10/15% faster in Castle/Imperial Age", 1, -49, 0],
    ["Can recruit War Chariots", 2, -49, 0],
    ["Gain access to Liu Bei", 3, -49, 0],
    ["Military production buildings and Docks provide +65 food", 1, -50, 0],
    ["Infantry regenerates 10/20/30 HP per minute in Feudal/Castle/Imperial Age", 2, -50, 0],
    ["Shock Infantry and Hei Guang Cavalry +2 attack in Imperial Age", 1, -50, 0],
    ["Careening, Dry Dock available one age earlier, cost and research time -75%", 2, -50, 0],
    ["Can recruit Jian Swordsmen", 2, -50, 0],
    ["Gain access to Sun Jian", 3, -50, 0],
    ["Receive one free Villager for each Mill, Lumber- and Mining Camp technology researched", 3, -51, 0],
    ["Hei Guang Cavalry and Xianbei Raider +15/30% HP in Castle/Imperial Age", 1, -51, 0],
    ["Trebuchet units cost -25%", 1, -51, 0],
    ["Can recruit Xianbei Raiders", 2, -51, 0],
    ["Gain access to Cao Cao", 3, -51, 0],
    ["Meat of hunted and livestock animals doesn't decay", 0, -52, 0],
    ["Mounted units and Fire Lancers attack +20% faster starting in Feudal Age", 3, -52, 0],
    ["Siege Engineers available in Castle Age", 2, -52, 0],
    ["Siege and Fortification upgrades cost -75% wood and research +100% faster", 1, -52, 0],
    ["Units receive -50% friendly fire damage", 0, -52, 0],
    ["Can recruit Grenadiers", 2, -52, 0],
    ["Pastures replace Farms and Mill upgrades", 2, -53, 0],
    ["Shepherds and Herders generate +10% additional food", 1, -53, 0],
    ["Melee attack upgrade effects are doubled", 2, -53, 0],
    ["Skirmishers, Spearman- and Scout Cavalry-line train and upgrade +25% faster", 1, -53, 0],
    ["Heavy Cavalry Archer upgrade available in Castle Age and costs -50%", 1, -53, 0],
    ["Can train Mounted Trebuchets", 2, -53, 0],
    ["Dragon Ships replace Fast Fire Ships", 2, -6, 0],
  ],

  // Unique Units (index 1 in original format)
  [
    ["Longbowmen", 2, -1, 0],
    ["Throwing Axemen", 0, -2, 0],
    ["Huskarls", 1, -3, 0],
    ["Teutonic Knights", 2, -4, 0],
    ["Samurai", 1, -5, 0],
    ["Chu Ko Nu", 1, -6, 0],
    ["Cataphracts", 1, -7, 0],
    ["Mamelukes", 1, -9, 0],
    ["War Elephants", 3, -8, 0],
    ["Janissaries", 2, -10, 0],
    ["Berserks", 1, -11, 0],
    ["Mangudai", 4, -12, 0],
    ["Woad Raiders", 0, -13, 0],
    ["Conquistadors", 2, -14, 0],
    ["Jaguar Warriors", 0, -15, 0],
    ["Plumed Archers", 1, -16, 0],
    ["Tarkans", 0, -17, 0],
    ["War Wagons", 0, -18, 0],
    ["Genoese Crossbowmen", 1, -19, 0],
    ["Ghulam", 0, -20, 0],
    ["Kamayuks", 0, -21, 0],
    ["Magyar Huszars", 0, -22, 0],
    ["Boyars", 2, -23, 0],
    ["Organ Guns", 3, -24, 0],
    ["Shotel Warriors", 0, -25, 0],
    ["Gbetos", 0, -26, 0],
    ["Camel Archers", 3, -27, 0],
    ["Ballista Elephants", 4, -28, 0],
    ["Karambit Warriors", 0, -29, 0],
    ["Arambai", 1, -30, 0],
    ["Rattan Archers", 1, -31, 0],
    ["Konniks", 1, -32, 0],
    ["Keshiks", 0, -33, 0],
    ["Kipchaks", 1, -34, 0],
    ["Leitis", 4, -35, 0],
    ["Coustilliers", 1, -36, 0],
    ["Serjeants", 0, -37, 0],
    ["Obuch", 2, -38, 0],
    ["Hussite Wagons", 2, -39, 0],
    ["Crusader Knights", 2, 1, 0],
    ["Xolotl Warriors", 1, 1, 0],
    ["Saboteurs", 3, 1, 0],
    ["Ninjas", 0, 1, 0],
    ["Flamethrowers", 3, 1, 0],
    ["Photonmen", 4, 1, 0],
    ["Centurions", 1, -43, 0],
    ["Apukispay", 0, 1, 0],
    ["Monkey Boys", 4, 1, 0],
    ["Amazon Warriors", 0, 1, 0],
    ["Amazon Archers", 1, 1, 0],
    ["Iroquois Warriors", 1, 1, 0],
    ["Varangian Guards", 0, 1, 0],
    ["Gendarmes", 1, 1, 0],
    ["Cuahchiqueh", 0, 1, 0],
    ["Ritterbruder", 1, 1, 0],
    ["Kazaks", 0, 1, 0],
    ["Szlachcic", 0, 1, 0],
    ["Cuirassiers", 1, 1, 0],
    ["Rajputs", 0, 1, 0],
    ["Seljuk Archers", 2, 1, 0],
    ["Numidian Javelinmen", 0, 1, 0],
    ["Sosso Guards", 0, 1, 0],
    ["Swiss Pikemen", 1, 1, 0],
    ["Headhunters", 3, 1, 0],
    ["Teulu", 0, 1, 0],
    ["Maillotins", 1, 1, 0],
    ["Hashashin", 1, 1, 0],
    ["Highlander", 0, 1, 0],
    ["Stradiot", 1, 1, 0],
    ["Ahosi", 1, 1, 0],
    ["Landsknecht", 0, 1, 0],
    ["Clibinarii", 0, 1, 0],
    ["Silahtar", 0, 1, 0],
    ["Jaridah", 2, 1, 0],
    ["Wolf Warriors", 1, 1, 0],
    ["Warrior Monks", 2, 1, 0],
    ["Castellan", 1, 1, 0],
    ["Wind Warriors", 1, 1, 0],
    ["Chakram Throwers", 4, -42, 0],
    ["Urumi Swordsmen", 1, -40, 0],
    ["Rathas", 1, -41, 0],
    ["Composite Bowmen", 3, -44, 0],
    ["Monaspa", 2, -45, 0],
    ["White Feather Guard", 2, -49, 0],
    ["Fire Archers", 3, -50, 0],
    ["Tiger Cavalry", 2, -51, 0],
    ["Iron Pagoda", 3, -52, 0],
    ["Liao Dao", 2, -53, 0],
  ],

  // Castle Age Unique Techs (index 2 in original, stored as index 2 here)
  [
    ["Atlatl (Skirmishers +1 attack, +1 range) [400F 350G]", 0, -15, 0],
    ["Kasbah (team Castles work 25% faster) [250F 250G]", 0, -27, 0],
    ["Yeomen (+1 foot archer and skirmisher range, +2 tower attack) [750W 450G]", 2, -1, 0],
    ["Stirrups (Cavalry attack 33% faster) [400F 200G]", 3, -32, 0],
    ["Burgundian Vineyards (Farmers slowly generate gold in addition to food) [400F 300G]", 2, -36, 0],
    ["Manipur Cavalry (Cavalry +4 attack vs. Ranged Soldiers) [300F 300G]", 0, -30, 0],
    ["Greek Fire (Fire ships +1 range, Bombard Towers and Dromons increased blast radius) [250F 300G]", 0, -7, 0],
    ["Stronghold (Castles, Kreposts and Towers fire 33% faster, Castles and Kreposts heal allied infantry in a 7 tile radius) [250F 200G]", 1, -13, 0],
    ["Great Wall (Walls and towers +30% HP) [400W 200S]", 0, -6, 0],
    ["Steppe Husbandry (Light Cavalry, Steppe Lancers and Cavalry Archers trained 100% faster) [200F 300W]", 1, -34, 0],
    ["Royal Heirs (Unique Unit and Camels receive -3 damage from Mounted Units) [300F 300G]", 1, -25, 0],
    ["Bearded Axe (Unique Unit +1 range) [300F 300G]", 4, -2, 0],
    ["Anarchy (create Unique Unit at barracks) [450F 250G]", 2, -3, 0],
    ["Marauders (create Unique Unit at stables) [300W 200G]", 2, -17, 0],
    ["Andean Sling (Skirmishers and Slingers no minimum range, Slingers +1 attack) [200F 300G]", 0, -21, 0],
    ["Grand Trunk Road (All gold income 10% faster, Market trading fee reduced to 10%) [250F 200W]", 1, -20, 0],
    ["Pavise (Archer-line, Condottiero, and Unique Unit +1/+1 armor) [200W 150G]", 1, 1, 0],
    ["Yasama (Towers shoot extra arrows) [300F 300W]", 2, -5, 0],
    ["Tusk Swords (Melee elephant units +3 attack) [300W 450G]", 3, -28, 0],
    ["Eupseong (Watch Towers, Guard Towers, and Keeps +2 range) [300F 300W]", 1, -18, 0],
    ["Hill Forts (Town Centers +3 range) [250F 250G]", 0, -35, 0],
    ["Corvinian Army (Unique Unit gold cost converted to additional food/wood cost) [200F 300G]", 4, -22, 0],
    ["Thalassocracy (upgrades Docks to Harbors, which fire arrows) [300F 300G]", 1, -29, 0],
    ["Tigui (Town Centers fire arrows when ungarrisoned) [200F 300W]", 0, -26, 0],
    ["Hul'che Javelineers (Skirmishers throw a second projectile) [300F 300G]", 1, -16, 0],
    ["Nomads (lost houses do not decrease population headroom) [300W 150G]", 0, -12, 0],
    ["Kamandaran (Archer-line gold cost is replaced by additional wood cost) [400F 300G]", 3, -8, 0],
    ["Carrack (Ships +1/+1 armor) [200W 300G]", 1, -24, 0],
    ["Madrasah (Monks return 50 gold when killed) [200F 100G]", 0, 1, 0],
    ["First Crusade (Each Town Center (maxiumum 5) spawns a one-time batch of 5 of your Unique Unit; units are more resistant to conversion) [400F 300G]", 3, -37, 0],
    ["Orthodoxy (Monk units +3/+3P armor) [200F 300G]", 1, 1, 0],
    ["Inquisition (Monk convert faster) [100F 300G]", 1, -14, 0],
    ["Silk Armor (Light Cavalry, Steppe Lancers and Cavalry Archers receive +1/+1P armor) [400W 300G]", 1, -33, 0],
    ["Ironclad (Siege units extra melee armor) [400W 350G]", 1, -4, 0],
    ["Sipahi (Cavalry Archers +20 HP) [350F 150G]", 2, -10, 0],
    ["Chatras (Elephant units +100 HP) [250F 250G]", 2, -31, 0],
    ["Chieftains (Infantry deal bonus damage to cavalry, generate gold when killing villagers, trade units, and monks) [600F 450G]", 1, -11, 0],
    ["Szlachta Privileges (Knight-line costs -60% gold) [500F 300G]", 3, -38, 0],
    ["Wagenburg Tactics (Gunpowder units move 15% faster) [300F 300G]", 1, -39, 0],
    ["Deconstruction (Siege units fire 33% faster) [400W 400G]", 2, 1, 0],
    ["Obsidian Arrows (Archer-line +6 attack vs. buildings) [300F 300G]", 3, 1, 0],
    ["Tortoise Engineers (Rams train 100% faster) [100W 200G]", 0, 1, 0],
    ["Panoply (Infantry +1/+1P armor, +1 attack) [300F 200G]", 2, 1, 0],
    ["Clout Archery (Archery Ranges work 50% faster) [150W 250G]", 1, 1, 0],
    ["Medical Corps (Elephant units regenerate 30 HP per minute) [300F 200G]", 1, -40, 0],
    ["Paiks (Unique Unit and elephant units attack 20% faster) [375W 275G]", 3, -41, 0],
    ["Kshatriyas (Military units cost -25% food) [500F 450G]", 3, -42, 0],
    ["Detinets (40% of Castle, Tower, Krepost, and Donjon stone cost replaced with wood) [400W 200G]", 2, -23, 0],
    ["Zealotry (Camel units +20 hit points) [400F 400G]", 1, 1, 0],
    ["Ballistas (Scorpions and Ballista Elephants fire 33% faster, Galleys +2 attack) [400W 300G]", 1, -43, 0],
    ["Bimaristan (Monk units automatically heal multiple nearby units) [300W 200G]", 0, -9, 0],
    ["Cilician Fleet (Demolition Ships +20% blast radius; Galley-line and Dromons +1 range) [350W 300G]", 0, -44, 0],
    ["Svan Towers (Defensive buildings +2 attack; towers fire arrows that pierce multiple units) [300F 200G]", 2, -45, 0],
    ["Replaceable Parts (Siege units +1/+1P armor, repairing siege is free) [400W 250G]", 2, 1, 0],
    ["Silk Road (Trade units cost -50%) [250F 250G]", 0, -19, 0],
    ["Coiled Serpent Array (Spearman-line and Unique Unit gain additional HP when near each other) [350F 300G]", 2, -49, 0],
    ["Red Cliff Tactics (Demolition Ships and Fire Archers deal fire damage to ships and buildings) [400F 250G]", 1, -50, 0],
    ["Tuntian (Soldiers passively produce food) [250F 300G]", 2, -51, 0],
    ["Fortified Bastions (Fortifications regenerate 500 HP per minute) [350F 250W]", 1, -52, 0],
    ["Lamellar Armor (Infantry and Skirmishers reflect 25% melee damage back to the attacker) [450F 300G]", 3, -53, 0],
  ],

  // Imperial Age Unique Techs (index 3 in original, stored as index 3 here)
  [
    ["Garland Wars (Infantry +4 attack) [450F 750G]", 2, -15, 0],
    ["Maghrebi Camels (Camel units regenerate) [700F 300G]", 1, -27, 0],
    ["Warwolf (Trebuchet units do blast damage) [800W 400G]", 1, -1, 0],
    ["Bagains (Militia-line gains +5 armor) [900F 450G]", 2, -32, 0],
    ["Flemish Revolution (Upgrades all existing Villagers to Flemish Militia; create Flemish Militia at Town Centers) [200F 150G + 10F 5G per villager]", 0, -36, 0],
    ["Howdah (Elephant units +1/+1P armor) [400F 300W]", 1, -30, 0],
    ["Logistica (Unique Unit causes trample damage) [800F 600G]", 4, -7, 0],
    ["Furor Celtica (Siege Workshop units +40% HP) [750F 450G]", 1, -13, 0],
    ["Rocketry (Scorpions, Rocket Carts and Lou Chuans +25% attack; Lou Chuans fire rockets) [1100W 900G]", 2, -6, 0],
    ["Elite Mercenaries (team members can train 5 free elite versions of your Unique Unit per castle) [650F 400G]", 0, -34, 0],
    ["Torsion Engines (increases blast radius of Siege Workshop units) [1000F 600G]", 3, -25, 0],
    ["Chivalry (Stables work 40% faster) [600W 500G]", 0, -2, 0],
    ["Perfusion (Barracks work 100% faster) [400W 600G]", 1, -3, 0],
    ["Atheism (+100 years for Relic, Wonder victories; enemy relics generate -50% resources) [500F 3OOW]", 0, -17, 0],
    ["Fabric Shields (Shock Infantry, Slingers, Unique Unit +1/+2 armor) [600F 600G]", 1, -21, 0],
    ["Shatagni (Hand Cannoneers +2 range) [500F 300G]", 0, -20, 0],
    ["Pirotechnia (Hand cannoneers deal +15% pass through damage and are more accurate) [650F 500G]", 2, -19, 0],
    ["Kataparuto (Trebuchet units fire, pack faster) [550W 300G]", 1, -5, 0],
    ["Double Crossbow (Scorpion and Ballista units fire two projectiles) [700F 400G]", 1, -28, 0],
    ["Shinkichon (Rocket Carts and Turtle Ships +1 range, fire additional rockets) [1100F 800G]", 0, -18, 0],
    ["Tower Shields (Spearmen and Skirmishers +2P armor) [500F 200G]", 1, -35, 0],
    ["Recurve Bow (Cavalry archers +1 range, +1 attack) [600W 400G]", 1, -22, 0],
    ["Forced Levy (Militia-line gold cost is replaced by additional food cost) [850F 500G]", 3, -29, 0],
    ["Farimba (Cavalry +5 attack) [650F 400G]", 4, -26, 0],
    ["El Dorado (Shock Infantry have +40 hit points) [750F 450G]", 2, -16, 0],
    ["Drill (Siege workshop units move 50% faster) [500W 450G]", 2, -12, 0],
    ["Citadels (Castles and Kreposts fire Bullets [+4 attack, +3 vs Rams, +3 vs Infantry], receive -25% bonus damage) [600W 300G]", 3, -8, 0],
    ["Arquebus (gunpowder units more accurate) [700F 400G]", 0, -24, 0],
    ["Counterweights (Trebuchet units and Mangonel-line +15% attack) [650F 500G]", 0, -9, 0],
    ["Hauberk (Knights +1/+2P armor) [700F 600G]", 1, -37, 0],
    ["Druzhina (Infantry damage adjacent units) [900F 500G]", 2, -23, 0],
    ["Supremacy (Villagers stronger in combat) [400F 250G]", 0, -14, 0],
    ["Timurid Siegecraft (Trebuchet units +2 range, enables Flaming Camels) [500W 400G]", 1, -33, 0],
    ["Crenellations (+3 range Castles garrisoned infantry fire arrows) [600F 400S]", 1, -4, 0],
    ["Artillery (+2 range Bombard Towers, Bombard Cannons, Cannon Galleons) [600F 650G]", 2, -10, 0],
    ["Paper Money (Lumberjacks slowly generate gold in addition to wood) [550F 200W]", 2, -31, 0],
    ["Bogsveigar (Foot Archers and Unique ships +1 attack) [650F 500G]", 0, -11, 0],
    ["Lechitic Legacy (Light Cavalry deals trample damage) [750F 550G]", 3, -38, 0],
    ["Hussite Reforms (Monks and Monastery upgrades have their gold cost replaced by food) [500F 450G]", 1, -39, 0],
    ["Brigandine Armor (Camels and Cavalry Archers +2/+1P armor) [500W 500G]", 1, 1, 0],
    ["Field Repairmen (Rams regain HP) [350W 650G]", 0, 1, 0],
    ["Golden Age (All buildings work 10% faster) [300S 600G]", 1, 1, 0],
    ["Villager's Revenge (Dead villagers become Halberdiers) [500F 250G]", 1, 1, 0],
    ["Gate Crashing (Ram gold cost is replaced by additional wood cost) [600W 700G]", 2, 1, 0],
    ["Wootz Steel (Infantry and cavalry attacks ignore armor) [650F 550G]", 4, -40, 0],
    ["Mahayana (Villagers and monk units take 10% less population space) [800W 650G]", 2, -41, 0],
    ["Frontier Guards (Camel units and Elephant Archers +4 melee armor) [800F 700G]", 1, -42, 0],
    ["Comitatenses (Militia-line, Knight-line, and Unique Unit train 50% faster and receive a 5 damage charge attack) [700F 800G]", 1, -43, 0],
    ["Fereters (Infantry except Spearmen +30 HP, Warrior Priests +100% heal speed) [550F 400G]", 2, -44, 0],
    ["Aznauri Cavalry (Cavalry units take 15% less population space) [750F 250G]", 1, -45, 0],
    ["Pila (Skirmisher attacks strip armour) [700F 600G]", 3, 1, 0],
    ["Enlistment (Infantry take 15% less population space) [700F 300G]", 1, 1, 0],
    ["Marshalled Hunters (Foot archers and skirmishers take 15% less population space) [750W 250G]", 1, 1, 0],
    ["Shigetō Yumi (Unique Unit, Mounted Archers, and Towers attack 15% faster and deal +2 anti-unique unit damage) [750F 350G]", 1, 1, 0],
    ["Bolt Magazine (Archer-line, Lou Chans, and War Chariots fire additional projectiles)", 3, -49, 0],
    ["Sitting Tiger (Trebuchet units fire additional projectiles) [600W, 300G]", 4, -50, 0],
    ["Ming Guang Armor (Mounted units +4 melee armor) [600F 450G]", 4, -51, 0],
    ["Thunderclap Bombs (Rocket Carts, Grenadiers, and Lou Chuans detonate when defeated; projectiles produce additional explosions) [900F 600G]", 2, -52, 0],
    ["Ordo Cavalry (Cavalry regenerates HP in combat) [600F 300G]", 2, -53, 0],
  ],

  // Team Bonuses (index 4 in original, stored as index 4 here)
  [
    ["Relics generate +33% gold", 2, -15, 0],
    ["Genitour available in the Archery Range starting in the Castle Age", 2, -27, 0],
    ["Archery Ranges work 10% faster", 3, -1, 0],
    ["Blacksmiths work 80% faster", 1, -32, 0],
    ["Relics generate both Gold and Food", 1, -36, 0],
    ["Relics visible on the map at the start of the game", 1, -30, 0],
    ["Monks +100% heal speed", 0, -7, 0],
    ["Siege Workshops work 20% faster", 1, -13, 0],
    ["Farms +10% food", 1, -6, 0],
    ["Palisade Walls +33% HP", 0, -34, 0],
    ["Outposts +3 LOS and cost no stone", 3, -25, 0],
    ["Knights +2 LOS", 0, -2, 0],
    ["Barracks work 20% faster", 3, -3, 0],
    ["Stables work 20% faster", 3, -17, 0],
    ["Start with a free Llama", 2, -21, 0],
    ["Camel and light cavalry units +2 attack vs. buildings", 1, -20, 0],
    ["Condottiero available in the Barracks in Imperial Age", 2, -19, 0],
    ["Galleys +4 LOS", 0, -5, 0],
    ["Scorpions +1 range", 3, -28, 0],
    ["Villagers +3 LOS", 0, -18, 0],
    ["Monasteries work 20% faster", 1, -35, 0],
    ["Cavalry Archers trained 25% faster", 1, -22, 0],
    ["Docks +6 LOS", 1, -29, 0],
    ["Universities work 80% faster", 1, -26, 0],
    ["Walls cost -50%", 2, -16, 0],
    ["Scout Cavalry, Light Cavalry, Hussar +2 LOS", 3, -12, 0],
    ["Knights +2 attack vs. Archers", 1, -8, 0],
    ["Technologies research 25% faster (excluding Age Up)", 0, -24, 0],
    ["Foot archers and skirmisher-line +2 attack vs. buildings", 2, -9, 0],
    ["Transport Ships +5 LOS and cost -50%", 0, -37, 0],
    ["Military buildings provide +5 population room", 0, -23, 0],
    ["Trade units generate +25% gold", 4, -14, 0],
    ["Cavalry Archers +2 LOS", 0, -33, 0],
    ["Units resist conversion", 4, -4, 0],
    ["Gunpowder units created 25% faster", 0, -10, 0],
    ["Imperial Skirmisher upgrade available in the Imperial Age", 3, -31, 0],
    ["Docks cost -15%", 0, -11, 0],
    ["Scout Cavalry, Light Cavalry, Hussar +1 attack vs. Ranged Soldiers", 0, -38, 0],
    ["Scorpion-line minimum range reduced", 0, -43, 0],
    ["Trade units +50 HP", 0, 1, 0],
    ["Houses built 100% faster", 0, -50, 0],
    ["Monks +2 LOS", 0, 1, 0],
    ["Herdables +2 LOS", 1, 1, 0],
    ["Mills, Lumber Camps, Mining Camps built 100% faster", 0, 1, 0],
    ["Unique Units +5% HP", 2, 1, 0],
    ["Skirmishers, Spearmen, and Scout-lines train 20% faster", 1, 1, 0],
    ["Fishing ships +2 LOS", 0, 1, 0],
    ["Scout-line +2 attack vs. gunpowder units", 0, 1, 0],
    ["Infantry +5 attack vs. Elephant units", 0, 1, 0],
    ["Explosive units +20% speed", 0, 1, 0],
    ["All resources last 5% longer", 2, 1, 0],
    ["Castles, Kreposts, Donjons work 10% faster", 2, 1, 0],
    ["Markets work 80% faster", 2, -39, 0],
    ["Steppe Lancers +3 LOS", 0, 1, 0],
    ["Spearmen +3 attack vs. cavalry", 1, 1, 0],
    ["Elephant units +4 attack vs. buildings", 1, 1, 0],
    ["Shock Infantry +2 LOS", 2, 1, 0],
    ["Docks work 20% faster", 1, 1, 0],
    ["Monasteries 3x HP", 0, 1, 0],
    ["Markets 3x HP", 0, 1, 0],
    ["Explosive units +6 LOS", 0, 1, 0],
    ["Outposts and towers constructed faster", 0, 1, 0],
    ["Siege towers +50% garrison capacity", 0, 1, 0],
    ["Docks built 100% faster", 0, 1, 0],
    ["Infantry +2 LOS", 2, -44, 0],
    ["Trade carts 20% faster when empty", 2, 1, 0],
    ["All explosive units +40% HP", 0, 1, 0],
    ["Town Centers +4 LOS", 0, 1, 0],
    ["Upgrading Unique Units to Elite costs -20%", 1, 1, 0],
    ["Docks provide +5 population room", 0, -40, 0],
    ["Trade units yield 10% food in addition to gold", 1, -41, 0],
    ["Camel and elephant units created 25% faster", 1, -42, 0],
    ["Can train spearmen from Town Centers", 2, 1, 0],
    ["Can train Canoes from docks", 2, 1, 0],
    ["Buildings cost 25% fewer resources to repair", 2, -45, 0],
    ["Mounted archers -50% frame delay", 1, 1, 0],
    ["Foot archers +2 LOS", 2, -49, 0],
    ["Cavalry +2 attack vs. siege weapons", 2, -51, 0],
    ["Gunpowder units +2 LOS", 0, -52, 0],
    ["Infantry +2 attack vs. Ranged Soldiers", 1, -53, 0],
  ],
]

/**
 * Get bonus cards for a specific type
 */
export function getBonusCards(type: BonusType): BonusCard[] {
  let descriptionIndex: number
  switch (type) {
    case 'civ':
      descriptionIndex = 0
      break
    case 'uu':
      descriptionIndex = 1
      break
    case 'castle':
      descriptionIndex = 2
      break
    case 'imp':
      descriptionIndex = 3
      break
    case 'team':
      descriptionIndex = 4
      break
    default:
      return []
  }

  const descriptions = cardDescriptions[descriptionIndex]
  return descriptions.map((desc, index) => ({
    id: index,
    name: desc[0], // Display name (same as description for bonus cards)
    description: desc[0], // Full description text
    rarity: desc[1],
    edition: desc[2],
    imageVersion: desc[3]
  }))
}

/**
 * Get the edition display name based on the edition value
 * Negative values indicate vanilla civ, 0 is base edition, positive are expansions
 */
export function getEditionName(edition: number): string {
  if (edition <= 0) {
    return editionNames[0] // Base Edition
  }
  return editionNames[Math.min(edition, editionNames.length - 1)]
}

export function useBonusData() {
  return {
    rarityNames,
    rarityCssClasses,
    editionNames,
    numCards,
    maxSelections,
    getBonusCards,
    getBonusImageUrl,
    getFrameUrl,
    getEditionUrl,
    getEditionName,
  }
}
