// Auto-generated enum for civBonuses indices
// Maps to descriptions in misc/strings.txt
// Mapping: strings.txt line N -> civBonuses[N-1]

#ifndef CIV_BONUS_ENUM_H
#define CIV_BONUS_ENUM_H

enum CivBonusIndex {
    CIV_BONUS_0_TOWN_CENTERS_COST_50_WOOD_STARTING_IN = 0, // Town Centers cost -50% wood starting in the Castle Age
    CIV_BONUS_1_FOOT_ARCHERS_EXCEPT_SKIRMISHERS_1_RANGE_IN = 1, // Foot archers (except skirmishers) +1 range in Castle and Imperial Age (+2 total)
    CIV_BONUS_2_SHEPHERDS_WORK_25_FASTER = 2, // Shepherds work 25% faster
    CIV_BONUS_3_CASTLES_COST_15_IN_CASTLE_25_IN_IMPERIAL_AGE = 3, // Castles cost -15% in Castle, -25% in Imperial Age
    CIV_BONUS_4_MOUNTED_UNITS_20_HIT_POINTS_STARTING_IN_FEUDAL_AGE = 4, // Mounted units +20% hit points starting in Feudal Age
    CIV_BONUS_5_FORAGERS_WORK_10_FASTER = 5, // Foragers work 10% faster
    CIV_BONUS_6_LOOM_CAN_BE_RESEARCHED_INSTANTLY = 6, // Loom can be researched instantly
    CIV_BONUS_7_VILLAGERS_5_ATTACK_VS_WILD_BOAR_HUNTERS = 7, // Villagers +5 attack vs. wild boar; hunters carry +15 meat; hunt contains +20% meat
    CIV_BONUS_8_10_POPULATION_IN_IMPERIAL_AGE = 8, // +10 population in Imperial Age
    CIV_BONUS_9_INFANTRY_1_ATTACK_VS_BUILDINGS_PER_AGE = 9, // Infantry +1 attack vs. buildings per age (starting from Feudal Age)
    CIV_BONUS_10_INFANTRY_COST_15_IN_DARK_20_IN = 10, // Infantry cost -15% in Dark, -20% in Feudal, -25% in Castle, -30% in Imperial Age
    CIV_BONUS_11_MONKS_DOUBLE_HEALING_RANGE = 11, // Monks double healing range
    CIV_BONUS_12_TOWERS_GARRISON_2X_UNITS_TOWN_CENTERS_GARRISON_10 = 12, // Towers garrison 2x units; Town Centers garrison +10
    CIV_BONUS_13_FARMS_COST_40 = 13, // Farms cost -40%
    CIV_BONUS_14_BARRACKS_AND_STABLE_UNITS_1_ARMOR_IN = 14, // Barracks and Stable units +1 armor in Castle and Imperial Age (+2 total)
    CIV_BONUS_15_ECONOMIC_DROP_OFF_BUILDINGS_COST_50 = 15, // Economic drop-off buildings cost -50%
    CIV_BONUS_16_FISHING_SHIPS_2X_HIT_POINTS_2P_ARMOR = 16, // Fishing Ships 2x hit points; +2P armor; work rate +5% Dark, +10% Feudal, +15% Castle, +20% Imperial Age
    CIV_BONUS_17_INFANTRY_ATTACK_33_FASTER_STARTING_IN_FEUDAL_AGE = 17, // Infantry attack 33% faster starting in Feudal Age
    CIV_BONUS_18_START_WITH_3_VILLAGERS_50_WOOD_200 = 18, // Start with +3 villagers, -50 wood, -200 food; Town Centers support 15 population and +7 LOS
    CIV_BONUS_19_DEMOLITION_SHIPS_50_HIT_POINTS = 19, // Demolition ships +50% hit points
    CIV_BONUS_20_TECHNOLOGIES_COST_5_FEUDAL_10_CASTLE_15 = 20, // Technologies cost -5% Feudal, -10% Castle, -15% Imperial Age
    CIV_BONUS_21_BUILDINGS_10_HP_DARK_20_FEUDAL_30 = 21, // Buildings +10% HP Dark, +20% Feudal, +30% Castle, +40% Imperial Age
    CIV_BONUS_22_FIRE_SHIPS_ATTACK_25_FASTER = 22, // Fire ships attack 25% faster
    CIV_BONUS_23_CAMEL_RIDERS_SKIRMISHERS_PIKEMEN_HALBERDIERS_COST_25 = 23, // Camel Riders, Skirmishers, Pikemen, Halberdiers cost -25%
    CIV_BONUS_24_START_WITH_50_WOOD_FOOD = 24, // Start with +50 wood, food
    CIV_BONUS_25_TOWN_CENTER_DOCK_2X_HIT_POINTS = 25, // Town Center, Dock 2x hit points
    CIV_BONUS_26_TOWN_CENTER_DOCK_WORK_RATE_5_DARK = 26, // Town Center, Dock work rate +5% Dark, +10% Feudal, +15% Castle, +20% Imperial Age
    CIV_BONUS_27_MARKET_COSTS_100_WOOD_MARKET_TRADE_COST_ONLY_5 = 27, // Market costs -100 wood; market trade cost only 5%
    CIV_BONUS_28_TRANSPORT_SHIPS_2X_HIT_POINTS_20_CARRY_CAPACITY = 28, // Transport Ships 2x hit points, +20 carry capacity
    CIV_BONUS_29_GALLEYS_ATTACK_25_FASTER = 29, // Galleys attack 25% faster
    CIV_BONUS_30_CAMEL_UNITS_25_HIT_POINTS = 30, // Camel units +25% hit points
    CIV_BONUS_31_GUNPOWDER_UNITS_25_HIT_POINTS = 31, // Gunpowder units +25% hit points
    CIV_BONUS_32_GOLD_MINERS_WORK_20_FASTER = 32, // Gold miners work 20% faster
    CIV_BONUS_33_SCOUT_CAVALRY_LIGHT_CAVALRY_HUSSAR_1_PIERCE_ARMOR = 33, // Scout Cavalry, Light Cavalry, Hussar +1 pierce armor
    CIV_BONUS_34_WARSHIPS_COST_15_FEUDAL_AGE_15_CASTLE = 34, // Warships cost -15% Feudal Age, -15% Castle Age, -20% Imperial Age
    CIV_BONUS_35_INFANTRY_20_HIT_POINTS_STARTING_IN_FEUDAL_AGE = 35, // Infantry +20% hit points starting in Feudal Age
    CIV_BONUS_36_CAVALRY_ARCHERS_FIRE_25_FASTER = 36, // Cavalry archers fire 25% faster
    CIV_BONUS_37_HUNTERS_WORK_40_FASTER = 37, // Hunters work 40% faster
    CIV_BONUS_38_LIGHT_CAVALRY_HUSSARS_STEPPE_LANCERS_20_30 = 38, // Light Cavalry, Hussars, Steppe Lancers +20/30% hit points in Castle/Imperial Age
    CIV_BONUS_39_INFANTRY_MOVES_5_10_15_20_FASTER = 39, // Infantry moves +5/10/15/20% faster in Dark/Feudal/Castle/Imperial Age
    CIV_BONUS_40_LUMBERJACKS_WORK_15_FASTER = 40, // Lumberjacks work 15% faster
    CIV_BONUS_41_SIEGE_UNITS_FIRE_25_FASTER = 41, // Siege units fire 25% faster
    CIV_BONUS_42_CAN_STEAL_SHEEP_AND_SHEEP_WITHIN_ONE = 42, // Can steal sheep, and sheep within one unit's LoS cannot be stolen
    CIV_BONUS_43_MISSIONARIES_CAN_BE_TRAINED_IN_MONASTERIES = 43, // Missionaries can be trained in monasteries
    CIV_BONUS_44_START_WITH_50_GOLD = 44, // Start with +50 gold
    CIV_BONUS_45_5_MONK_HIT_POINTS_FOR_EACH_MONASTERY_TECHNOLOGY = 45, // +5 Monk hit points for each Monastery technology
    CIV_BONUS_46_START_WITH_1_VILLAGER_BUT_50_FOOD = 46, // Start with +1 villager, but -50 food
    CIV_BONUS_47_CAVALRY_ARCHERS_COST_10_CASTLE_20_IMPERIAL_AGE = 47, // Cavalry Archers cost -10% Castle, -20% Imperial Age
    CIV_BONUS_48_RANGED_SOLDIERS_AND_INFANTRY_COST_50_WOOD = 48, // Ranged Soldiers and Infantry cost -50% wood
    CIV_BONUS_49_ARCHER_ARMOR_UPGRADES_FREE = 49, // Archer armor upgrades free
    CIV_BONUS_50_CAN_TRAIN_TURTLE_SHIPS_IN_DOCKS = 50, // Can train Turtle Ships in docks
    CIV_BONUS_51_CAN_RECRUIT_LONGBOATS_FROM_DOCKS = 51, // Can recruit Longboats from docks
    CIV_BONUS_52_GUNPOWDER_UNITS_COST_20 = 52, // Gunpowder units cost -20%
    CIV_BONUS_53_CAN_UPGRADE_HEAVY_CAMEL_RIDERS_TO_IMPERIAL = 53, // Can upgrade Heavy Camel Riders to Imperial Camel Riders
    CIV_BONUS_54_FISHERMEN_WORK_10_FASTER = 54, // Fishermen work 10% faster
    CIV_BONUS_55_STABLE_UNITS_1P_ARMOR_IN_CASTLE_AND = 55, // Stable units +1P armor in Castle and Imperial Age (+2 total)
    CIV_BONUS_56_VILLAGERS_COST_8_DARK_13_FEUDAL_18 = 56, // Villagers cost -8% Dark, -13% Feudal, -18% Castle, -23% Imperial Age
    CIV_BONUS_57_MILITARY_UNITS_COST_10_15_20_25 = 57, // Military units cost -10, 15, 20, 25% food in Dark, Feudal, Castle, Imperial
    CIV_BONUS_58_BUILDINGS_COST_15_STONE = 58, // Buildings cost -15% stone
    CIV_BONUS_59_HOUSES_SUPPORT_10_POPULATION = 59, // Houses support 10 population
    CIV_BONUS_60_VILLAGERS_AFFECTED_BY_BLACKSMITH_UPGRADES_STARTING_IN = 60, // Villagers affected by Blacksmith upgrades starting in the Castle Age
    CIV_BONUS_61_CAN_RECRUIT_SLINGERS_FROM_ARCHERY_RANGES = 61, // Can recruit slingers from Archery Ranges
    CIV_BONUS_62_VILLAGERS_KILL_WOLVES_WITH_1_STRIKE = 62, // Villagers kill wolves with 1 strike
    CIV_BONUS_63_SCOUT_CAVALRY_LIGHT_CAVALRY_HUSSAR_COST_15 = 63, // Scout Cavalry, Light Cavalry, Hussar cost -15%
    CIV_BONUS_64_SIEGE_WORKSHOP_UNITS_15_CHEAPER = 64, // Siege Workshop units 15% cheaper
    CIV_BONUS_65_ALL_UNITS_COST_20_GOLD = 65, // All units cost -20% gold
    CIV_BONUS_66_FORAGERS_GENERATE_A_TRICKLE_OF_WOOD_33 = 66, // Foragers generate a trickle of wood (33%)
    CIV_BONUS_67_SHIPS_10_HP = 67, // Ships +10% HP
    CIV_BONUS_68_CAN_BUILD_FEITORIA_IN_IMPERIAL_AGE = 68, // Can build Feitoria in Imperial Age
    CIV_BONUS_69_CAN_BUILD_CARAVELS_IN_DOCKS = 69, // Can build Caravels in docks
    CIV_BONUS_70_FOOT_ARCHERS_FIRE_18_FASTER = 70, // Foot archers fire 18% faster
    CIV_BONUS_71_RECEIVE_100_GOLD_100_FOOD_WHEN_ADVANCING = 71, // Receive +100 gold, +100 food when advancing to the next age
    CIV_BONUS_72_PIKEMAN_UPGRADE_FREE = 72, // Pikeman upgrade free
    CIV_BONUS_73_BUILDINGS_COST_15_WOOD = 73, // Buildings cost -15% wood
    CIV_BONUS_74_BARRACKS_UNITS_1_PIERCE_ARMOR_PER_AGE = 74, // Barracks units +1 pierce armor per age (starting from Feudal Age)
    CIV_BONUS_75_VILLAGERS_DROP_OFF_10_MORE_GOLD = 75, // Villagers drop off 10% more gold
    CIV_BONUS_76_VILLAGERS_MOVE_5_FASTER_IN_DARK_AGE = 76, // Villagers move 5% faster in Dark Age, 10% faster in Feudal Age
    CIV_BONUS_77_SHIPS_MOVE_10_FASTER = 77, // Ships move 10% faster
    CIV_BONUS_78_STABLE_UNITS_COST_15_IN_CASTLE_20_IN_IMPERIAL_AGE = 78, // Stable units cost -15% in Castle, -20% in Imperial Age
    CIV_BONUS_79_MELEE_ELEPHANT_UNITS_MOVE_10_FASTER = 79, // Melee elephant units move 10% faster
    CIV_BONUS_80_VILLAGERS_CAN_GARRISON_IN_HOUSES = 80, // Villagers can garrison in Houses
    CIV_BONUS_81_NO_BUILDINGS_REQUIRED_TO_ADVANCE_TO_THE = 81, // No buildings required to advance to the next age or to unlock other buildings
    CIV_BONUS_82_ADVANCE_TO_THE_NEXT_AGE_66_FASTER = 82, // Advance to the next age 66% faster
    CIV_BONUS_83_ELEPHANT_UNITS_COST_25_CASTLE_35_IN_IMPERIAL_AGE = 83, // Elephant units cost -25% Castle, -35% in Imperial Age
    CIV_BONUS_84_FISH_TRAPS_COST_33_AND_PROVIDE_200_FOOD = 84, // Fish Traps cost -33% and provide +200% food
    CIV_BONUS_85_FOOT_ARCHERS_AND_CONDOTTIERI_1_MELEE_1 = 85, // Foot Archers and Condottieri +1 melee/+1 pierce armor
    CIV_BONUS_86_LUMBER_CAMP_UPGRADES_FREE = 86, // Lumber Camp upgrades free
    CIV_BONUS_87_INFANTRY_1_ATTACK_PER_AGE_STARTING_IN = 87, // Infantry +1 attack per age (starting in the Feudal Age)
    CIV_BONUS_88_MONASTERY_TECHNOLOGIES_COST_50 = 88, // Monastery technologies cost -50%
    CIV_BONUS_89_ENEMY_POSITIONS_ARE_REVEALED_AT_THE_START = 89, // Enemy positions are revealed at the start of the game
    CIV_BONUS_90_ARCHERY_RANGE_UNITS_AND_FIRE_LANCERS_20_HP = 90, // Archery Range units and Fire Lancers +20% HP
    CIV_BONUS_91_MILITIA_LINE_UPGRADES_FREE = 91, // Militia-line upgrades free
    CIV_BONUS_92_TOWN_CENTERS_COST_50_STONE_STARTING_IN = 92, // Town Centers cost -50% stone starting in the Castle Age
    CIV_BONUS_93_CAN_BUILD_KREPOST = 93, // Can build Krepost
    CIV_BONUS_94_LIVESTOCK_ANIMALS_LAST_50_LONGER = 94, // Livestock animals last +50% longer
    CIV_BONUS_95_UNITS_DEAL_25_DAMAGE_WHEN_FIGHTING_FROM = 95, // Units deal +25% damage when fighting from higher elevation
    CIV_BONUS_96_THUMB_RING_PARTHIAN_TACTICS_FREE = 96, // Thumb Ring, Parthian Tactics free
    CIV_BONUS_97_MOUNTED_UNITS_5_FASTER_EACH_AGE_STARTING = 97, // Mounted units 5% faster each age (starting in Feudal Age)
    CIV_BONUS_98_ADDITIONAL_TOWN_CENTER_CAN_BE_BUILT_IN = 98, // Additional Town Center can be built in the Feudal Age
    CIV_BONUS_99_SIEGE_WORKSHOP_AND_BATTERING_RAM_AVAILABLE_IN = 99, // Siege Workshop and Battering Ram available in the Feudal Age; Capped Ram upgrade available in Castle Age
    CIV_BONUS_100_RECEIVE_100_FOOD_PER_TOWN_CENTER = 100, // Receive +100 food per Town Center
    CIV_BONUS_101_SPEARMEN_AND_SKIRMISHERS_MOVE_10_FASTER = 101, // Spearmen and Skirmishers move 10% faster
    CIV_BONUS_102_EACH_GARRISONED_RELIC_GIVES_1_ATTACK_TO = 102, // Each garrisoned relic gives +1 attack to Knights and Unique Unit (maximum +4)
    CIV_BONUS_103_CAVALIER_UPGRADE_AVAILABLE_IN_CASTLE_AGE = 103, // Cavalier upgrade available in Castle Age
    CIV_BONUS_104_GUNPOWDER_UNITS_25_ATTACK = 104, // Gunpowder units +25% attack
    CIV_BONUS_105_ECONOMIC_UPGRADES_COST_33_FOOD_AND_AVAILABLE = 105, // Economic upgrades cost -33% food and available one age earlier
    CIV_BONUS_106_FORTIFICATIONS_BUILT_50_TOWN_CENTERS_BUILT_100 = 106, // Fortifications built 50%, Town Centers built 100% faster
    CIV_BONUS_107_SOLDIERS_RECEIVE_33_LESS_BONUS_DAMAGE = 107, // Soldiers receive 33% less bonus damage
    CIV_BONUS_108_FARM_UPGRADES_PROVIDE_125_ADDITIONAL_FOOD = 108, // Farm upgrades provide +125% additional food
    CIV_BONUS_109_CAN_BUILD_DONJON = 109, // Can build Donjon
    CIV_BONUS_120_FARMERS_WORK_15_FASTER = 120, // Farmers work 15% faster
    CIV_BONUS_133_FOOT_ARCHERS_AND_SKIRMISHERS_COST_10_FEUDAL = 133, // Foot archers and skirmishers cost -10% Feudal, -20% Castle, -30% Imperial Age
    CIV_BONUS_134_LUMBERJACKS_GENERATE_FOOD_IN_ADDITION_TO_WOOD = 134, // Lumberjacks generate food in addition to wood
    CIV_BONUS_135_STONE_MINERS_WORK_20_FASTER = 135, // Stone miners work 20% faster
    CIV_BONUS_139_NEW_TOWN_CENTERS_SPAWN_2_SHEEP_STARTING = 139, // New Town Centers spawn 2 sheep starting in the Castle Age
    CIV_BONUS_140_WONDERS_DON_T_COST_WOOD_AND_PROVIDE = 140, // Wonders don't cost wood and provide +50 to population limit (max 1)
    CIV_BONUS_142_VILLAGERS_REGENERATE_10_HP_MIN_IN_FEUDAL = 142, // Villagers regenerate 10 HP/min in Feudal, 15 in Castle, 20 in Imperial Age
    CIV_BONUS_175_START_WITH_100_STONE = 175, // Start with +100 stone
    CIV_BONUS_192_TOWN_CENTERS_SPAWN_2_VILLAGERS_WHEN_THE = 192, // Town Centers spawn 2 villagers when the next Age is reached
    CIV_BONUS_193_CAN_RECRUIT_WARRIOR_PRIESTS = 193, // Can recruit Warrior Priests
    CIV_BONUS_204_FISHERMEN_AND_FISHING_SHIPS_CARRY_15 = 204, // Fishermen and Fishing Ships carry +15
    CIV_BONUS_209_STONE_WALLS_AVAILABLE_IN_DARK_AGE = 209, // Stone Walls available in Dark Age
    CIV_BONUS_211_VILLAGERS_RETURN_25_FOOD_ON_DEATH = 211, // Villagers return 25 food on death
    CIV_BONUS_218_COMPLETED_CASTLES_PROVIDE_400_GOLD_AS_LONG = 218, // Completed castles provide 400 gold as long as they stay standing
    CIV_BONUS_220_MELEE_CAVALRY_GAIN_2_BONUS_DAMAGE_VS_SKIRMISHERS = 220, // Melee Cavalry gain +2 bonus damage vs Skirmishers
    CIV_BONUS_221_SPEARMAN_AND_MILITIA_LINE_UPGRADES_EXCEPT_MAN = 221, // Spearman- and Militia-line upgrades (except Man-at-Arms) available one age earlier
    CIV_BONUS_226_SIEGE_UNITS_COST_33_WOOD = 226, // Siege units cost -33% wood
    CIV_BONUS_229_RAMS_GENERATE_STONE_BY_RAMMING = 229, // Rams generate stone by ramming
    CIV_BONUS_239_CAN_UPGRADE_FORTIFIED_WALLS_TO_CITY_WALLS = 239, // Can upgrade Fortified Walls to City Walls in Imperial Age
    CIV_BONUS_247_PARTHIAN_TACTICS_AVAILABLE_IN_CASTLE_AGE = 247, // Parthian Tactics available in Castle Age
    CIV_BONUS_257_ALL_VILLAGERS_WORK_5_FASTER = 257, // All villagers work 5% faster
    CIV_BONUS_269_TOWERS_DEAL_EXTRA_DAMAGE_TO_CAVALRY = 269, // Towers deal extra damage to cavalry
    CIV_BONUS_270_CAN_BUILD_MONASTERY_IN_FEUDAL_AGE_MONKS = 270, // Can build Monastery in Feudal Age; Monks recruited in Feudal Age have longer conversions and cannot pickup relics
    CIV_BONUS_280_FOLWARK_REPLACES_MILL = 280, // Folwark replaces Mill
    CIV_BONUS_281_STONE_MINERS_GENERATE_GOLD_IN_ADDITION_TO_STONE = 281, // Stone Miners generate gold in addition to stone
    CIV_BONUS_282_WINGED_HUSSAR_REPLACES_HUSSAR = 282, // Winged Hussar replaces Hussar
    CIV_BONUS_283_CHEMISTRY_AND_HAND_CANNONEER_AVAILABLE_IN_CASTLE = 283, // Chemistry and Hand Cannoneer available in Castle Age
    CIV_BONUS_284_SPEARMEN_DEALS_25_BONUS_DAMAGE = 284, // Spearmen deals +25% bonus damage
    CIV_BONUS_285_FERVOR_AND_SANCTITY_AFFECTS_VILLAGERS = 285, // Fervor and Sanctity affects villagers
    CIV_BONUS_286_CAN_UPGRADE_BOMBARD_CANNONS_TO_HOUFNICE = 286, // Can upgrade Bombard Cannons to Houfnice
    CIV_BONUS_287_CAN_BUILD_CARAVANSERI_IN_IMPERIAL_AGE = 287, // Can build Caravanseri in Imperial Age
    CIV_BONUS_288_GUNPOWDER_UNITS_1_1P_ARMOR = 288, // Gunpowder units +1/+1P armor
    CIV_BONUS_289_RECEIVE_200_WOOD_WHEN_ADVANCING_TO_THE_NEXT_AGE = 289, // Receive +200 wood when advancing to the next age
    CIV_BONUS_290_BARRACKS_TECHNOLOGIES_COST_50 = 290, // Barracks technologies cost -50%
    CIV_BONUS_291_SKIRMISHERS_AND_ELEPHANT_ARCHERS_ATTACK_25_FASTER = 291, // Skirmishers and Elephant Archers attack 25% faster
    CIV_BONUS_292_ELEPHANT_UNITS_RECEIVE_25_LESS_BONUS_DAMAGE = 292, // Elephant units receive 25% less bonus damage and are more resistant to conversion
    CIV_BONUS_293_SHIPS_REGENERATE_15_HP_PER_MINUTE = 293, // Ships regenerate 15 HP per minute
    CIV_BONUS_294_START_WITH_2_FORAGE_BUSHES = 294, // Start with 2 Forage Bushes
    CIV_BONUS_295_CAN_GARRISON_MILLS_WITH_LIVESTOCK_TO_PRODUCE_FOOD = 295, // Can garrison Mills with livestock to produce food
    CIV_BONUS_296_MOUNTED_UNITS_DEAL_20_BONUS_DAMAGE_FEUDAL = 296, // Mounted units deal +20% bonus damage Feudal, +30% Castle, +40% Imperial Age
    CIV_BONUS_297_CAN_GARRISON_DOCKS_WITH_FISHING_SHIPS = 297, // Can garrison Docks with Fishing Ships
    CIV_BONUS_298_CAN_TRAIN_THIRISADAI_IN_DOCKS = 298, // Can train Thirisadai in docks
    CIV_BONUS_299_CAN_RECRUIT_SHRIVAMSHA_RIDERS = 299, // Can recruit Shrivamsha Riders
    CIV_BONUS_300_CAN_RECRUIT_CAMEL_SCOUTS_IN_FEUDAL_AGE = 300, // Can recruit Camel Scouts in Feudal Age
    CIV_BONUS_301_GAIN_20_GOLD_FOR_EACH_TECHNOLOGY_RESEARCHED = 301, // Gain 20 gold for each technology researched
    CIV_BONUS_303_ELEPHANT_UNITS_1_1P_ARMOR = 303, // Elephant units +1/+1P armor
    CIV_BONUS_304_MONK_UNITS_3_3P_ARMOR = 304, // Monk units +3/+3P armor
    CIV_BONUS_305_INFANTRY_RECEIVES_DOUBLE_EFFECT_FROM_BLACKSMITH_ARMOR = 305, // Infantry receives double effect from Blacksmith armor upgrades
    CIV_BONUS_306_SCORPIONS_COST_60_GOLD_AND_BENEFIT_FROM = 306, // Scorpions cost -60% gold and benefit from Ballistics research
    CIV_BONUS_307_LEGIONARY_REPLACES_TWO_HANDED_SWORDSMAN_CHAMPION = 307, // Legionary replaces Two-Handed Swordsman / Champion
    CIV_BONUS_308_CAN_UPGRADE_HEAVY_SCORPIONS_TO_IMPERIAL_SCORPIONS = 308, // Can upgrade Heavy Scorpions to Imperial Scorpions
    CIV_BONUS_309_CAN_UPGRADE_ELITE_BATTLE_ELEPHANTS_TO_ROYAL = 309, // Can upgrade Elite Battle Elephants to Royal Battle Elephants
    CIV_BONUS_310_CAN_UPGRADE_ELITE_STEPPE_LANCERS_TO_ROYAL_LANCERS = 310, // Can upgrade Elite Steppe Lancers to Royal Lancers
    CIV_BONUS_311_CAVALRY_ARCHERS_2_ATTACK_VS_ARCHERS_EXCEPT = 311, // Cavalry Archers +2 attack vs. Archers (except skirmishers)
    CIV_BONUS_312_WOOD_AND_MINING_UPGRADES_ARE_40_MORE = 312, // Wood and mining upgrades are 40% more effective, economic drop-off buildings cost -25%
    CIV_BONUS_313_FIRST_RELIGIOUS_BUILDING_RECEIVES_A_FREE_RELIC = 313, // First religious building receives a free relic
    CIV_BONUS_314_SAVAR_REPLACES_PALADIN = 314, // Savar replaces Paladin
    CIV_BONUS_315_GALLEY_LINE_AND_DROMONS_FIRE_AN_ADDITIONAL = 315, // Galley-line and Dromons fire an additional projectile
    CIV_BONUS_316_FORTIFIED_CHURCH_REPLACES_MONASTERY = 316, // Fortified church replaces monastery
    CIV_BONUS_317_MULE_CARTS_REPLACE_LUMBER_CAMPS_AND_MINING_CAMPS = 317, // Mule Carts replace Lumber Camps and Mining Camps
    CIV_BONUS_318_START_WITH_A_MULE_CART = 318, // Start with a Mule Cart
    CIV_BONUS_319_RELIGIOUS_BUILDINGS_PROVIDE_VILLAGERS_IN_AN_8 = 319, // Religious buildings provide Villagers in an 8 tile radius with +10% work rate
    CIV_BONUS_320_UNITS_AND_BUILDINGS_RECEIVE_15_DAMAGE_WHEN = 320, // Units and buildings receive -15% damage when fighting from higher elevation
    CIV_BONUS_321_MOUNTED_UNITS_REGENERATE_2_8_14_HP = 321, // Mounted units regenerate 2/8/14 HP per minute, in the Feudal, Castle, Imperial Age
    CIV_BONUS_322_FLAMING_CAMELS_AVAILABLE_IN_SIEGE_WORKSHOPS_IN = 322, // Flaming Camels available in Siege Workshops in Imperial Age
    CIV_BONUS_325_HUSBANDRY_AFFECTS_ATTACK_SPEED = 325, // Husbandry affects attack speed
    CIV_BONUS_327_BLACKSMITH_UPGRADES_AFFECT_BONUS_DAMAGE = 327, // Blacksmith upgrades affect bonus damage
    CIV_BONUS_329_FARMERS_DON_T_REQUIRE_MILLS_TOWN_CENTERS = 329, // Farmers don't require Mills/Town Centers to drop off food
    CIV_BONUS_332_KNIGHTS_AVAILABLE_IN_FEUDAL_AGE_WITH_30HP = 332, // Knights available in Feudal Age with 30HP
    CIV_BONUS_333_SIEGE_TOWERS_CAN_FIRE_ARROWS = 333, // Siege Towers can fire arrows
    CIV_BONUS_334_FIRE_LANCERS_AND_FIRE_SHIPS_MOVE_5 = 334, // Fire Lancers and Fire Ships move +5/10% faster in Castle/Imperial Age
    CIV_BONUS_335_ARCHERY_UNIT_TECHNOLOGIES_AT_THE_ARCHERY_RANGE = 335, // Archery Unit technologies at the Archery Range and Blacksmith cost -25%
    CIV_BONUS_336_SIEGE_WEAPONS_AND_SIEGE_WARSHIPS_MOVE_10 = 336, // Siege Weapons and Siege Warships move +10/15% faster in Castle/Imperial Age
    CIV_BONUS_337_CAN_RECRUIT_WAR_CHARIOTS = 337, // Can recruit War Chariots
    CIV_BONUS_338_GAIN_ACCESS_TO_LIU_BEI = 338, // Gain access to Liu Bei
    CIV_BONUS_339_MILITARY_PRODUCTION_BUILDINGS_AND_DOCKS_PROVIDE_65 = 339, // Military production buildings and Docks provide +65 food
    CIV_BONUS_340_INFANTRY_REGENERATES_10_20_30_HP_PER = 340, // Infantry regenerates 10/20/30 HP per minute in Feudal/Castle/Imperial Age
    CIV_BONUS_341_JIAN_SWORDSMEN_AND_HEI_GUANG_CAVALRY_2 = 341, // Jian Swordsmen and Hei Guang Cavalry +2 attack in Imperial Age
    CIV_BONUS_342_CAREENING_DRY_DOCK_AVAILABLE_ONE_AGE_EARLIER = 342, // Careening, Dry Dock available one age earlier, cost and research time -75%
    CIV_BONUS_343_CAN_RECRUIT_JIAN_SWORDSMEN = 343, // Can recruit Jian Swordsmen
    CIV_BONUS_344_GAIN_ACCESS_TO_SUN_JIAN = 344, // Gain access to Sun Jian
    CIV_BONUS_345_RECEIVE_ONE_FREE_VILLAGER_FOR_EACH_MILL = 345, // Receive one free Villager for each Mill, Lumber- and Mining Camp technology researched
    CIV_BONUS_346_HEI_GUANG_CAVALRY_AND_XIANBEI_RAIDER_15 = 346, // Hei Guang Cavalry and Xianbei Raider +15/30% HP in Castle/Imperial Age
    CIV_BONUS_347_TRACTION_TREBUCHETS_AND_LOU_CHUANS_COST_25 = 347, // Traction Trebuchets and Lou Chuans cost -25%
    CIV_BONUS_348_CAN_RECRUIT_XIANBEI_RAIDERS = 348, // Can recruit Xianbei Raiders
    CIV_BONUS_349_GAIN_ACCESS_TO_CAO_CAO = 349, // Gain access to Cao Cao
    CIV_BONUS_350_MEAT_OF_HUNTED_AND_LIVESTOCK_ANIMALS_DOESN_T_DECAY = 350, // Meat of hunted and livestock animals doesn't decay
    CIV_BONUS_351_MOUNTED_UNITS_AND_FIRE_LANCERS_ATTACK_20 = 351, // Mounted units and Fire Lancers attack +20% faster starting in Feudal Age
    CIV_BONUS_352_SIEGE_ENGINEERS_AVAILABLE_IN_CASTLE_AGE = 352, // Siege Engineers available in Castle Age
    CIV_BONUS_353_SIEGE_AND_FORTIFICATION_UPGRADES_COST_75_WOOD = 353, // Siege and Fortification upgrades cost -75% wood and research +100% faster
    CIV_BONUS_354_UNITS_RECEIVE_50_FRIENDLY_FIRE_DAMAGE = 354, // Units receive -50% friendly fire damage
    CIV_BONUS_355_CAN_RECRUIT_GRENADIERS = 355, // Can recruit Grenadiers
    CIV_BONUS_356_PASTURES_REPLACE_FARMS_AND_MILL_UPGRADES = 356, // Pastures replace Farms and Mill upgrades
    CIV_BONUS_357_SHEPHERDS_AND_HERDERS_GENERATE_10_ADDITIONAL_FOOD = 357, // Shepherds and Herders generate +10% additional food
    CIV_BONUS_358_MELEE_ATTACK_UPGRADE_EFFECTS_ARE_DOUBLED = 358, // Melee attack upgrade effects are doubled
    CIV_BONUS_359_SKIRMISHERS_SPEARMAN_AND_SCOUT_CAVALRY_LINE_TRAIN = 359, // Skirmishers, Spearman- and Scout Cavalry-line train and upgrade +25% faster
    CIV_BONUS_360_HEAVY_CAVALRY_ARCHER_UPGRADE_AVAILABLE_IN_CASTLE = 360, // Heavy Cavalry Archer upgrade available in Castle Age and costs -50%
    CIV_BONUS_361_CAN_TRAIN_MOUNTED_TREBUCHETS = 361, // Can train Mounted Trebuchets
    CIV_BONUS_362_BONUS_362 = 362, // BONUS_362
};

#endif // CIV_BONUS_ENUM_H
